# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e00b42efb90b9dd3bed821d208f9f272f7a203c66c77bb0438d0a29b06125e77416748f535db2ab39a039dca9dfe8d26e740f9b7649fb9fa97382e6db92d953

test:
  secret_key_base: fbd50e3158a64b4879f8c11efecf936bda0f30072afa83756e4dbc7ab680171ec1c7ed65a3c49178f9dbf261f7bc7176a1d7032010dd7217a93e04cabdfc8183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
