# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e843db0dee942ce890d690722051d0eb59b09c2a50cf97d7749662429cf39bf5a1b9ada9eea76fcda01922b1c6d4427ff17d4d2c2e9388322bca40f1a6c7cf59

test:
  secret_key_base: 4b0f33452e205362448203ec9af95d4ace51e59f0612322840cd84c0a9d197174ebbba0cb6a524b07648ef1c2df89fcec88bab85505febdb9c9a8ed81802eb73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
