# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas_app', '0002_auto_20180321_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
