# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ffdb232987d7656d92e4b45ce55f3ec2dbfd66f0f1e75b9f606a34c6e6b5116a56f9214b56b235f6fe120402b8619792d6962e677d5bbb57ddf410eeb25eb1

test:
  secret_key_base: 03bb13ce382702c4c69ad5e2eb7e4d659947dcbb2520b5eaccd988892a6a214e775a93f5a9d2a2cca2a436b3869606f6f465602cdc7810f2dca400191d73426c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
