# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99a2951132e7c854770e79736f59e0bcc83bcd0ef194b10a8195c0913784a0a019a4fbe96cd1669fab9b79742d87af749d5324875e35625cb3ffd830cda78d1c

test:
  secret_key_base: 8bf12c220041614cb85ca7858fa5bc023f1beda056146c1098d6a993c3c22c16b68430caa6a411edad6d71f78101a1166d890ca35dc66b18258a5957df6bff51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
