# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
